language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
install:
    - pip install .
script:
    - python -c 'import ZODB, ZEO, BTrees, persistent, transaction'
notifications:
    email: false
